---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a vpc and a single public subnet for Cloud9 environments
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
        - CostCenter
  Version:
    Description: 1.2
Parameters:
  CostCenter:
    Type: String
    MinLength: 5
    MaxLength: 7
    Description: "CostCenter - must be lower-case, limit 4 characters"
    AllowedPattern: "\\d{5,7}"
Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 60
      Description: Linux Instance
      InstanceType: t2.micro
      # Name: String
      # OwnerArn: String
      # Repositories: 
      #   - Repository
      SubnetId: 
        Fn::ImportValue: 
          !Sub ${AWS::Region}-Cloud9-Subnet
      Tags: 
        - Key: CostCenter
          Value: !Ref CostCenter

#Outputs:


